### ISSUE TITLE
Chinese Website with English Subtitles

### ISSUE THREAD

**Issue by OshekharO** [821938089/cloudstream-extensions#1]
Hii, can you please make extension of Chinese web having movies and tv series with English Subtitles?

Google Translated:-

你好，请问你能扩展中文网有英文字幕的电影和电视剧吗？

**Comment by 821938089** [comment]
Can you provide some websites with English subtitles?
I can't find websites with English subtitles for Chinese movies and TV series.

I recommend you to use English extensions (such as SoraStream) to watch Chinese movies and TV series which have English subtitles.

**Comment by OshekharO** [comment]
https://www.betaseries.com
https://dramacool.city
https://kshow123online.com
https://123animehub.cc

Bro check this site's out.

**Comment by 821938089** [comment]
Added dramacool, kshow123, 123animehub extension.
May be a little rough, hope dont care.

**Comment by OshekharO** [comment]
Thankyou brother 😄
