### ISSUE TITLE
Search Not Working 

### ISSUE THREAD

**Issue by OshekharO** [821938089/cloudstream-extensions#11]
Search is not working also in bollyzone HomePageList("Latest Episode Updates") not showing.

1: https://desicinemas.tv
2: https://www.bollyzone.tv

Provider: https://github.com/821938089/cloudstream-extensions/tree/master/DesicinemasProvider/src/main/kotlin/com/horis/cloudstreamplugins

Also in homepage list you can add:

https://desicinemas.tv/category/punjabi/
https://desicinemas.tv/category/bollywood/
https://desicinemas.tv/category/hindi-dubbed/

**Comment by OshekharO** [comment]
Still https://www.bollyzone.tv contents are not showing.

**Comment by 821938089** [comment]
What contents?

**Comment by OshekharO** [comment]
> What contents?

Series which are available on https://www.bollyzone.tv/ is not showing in cloudstream

**Comment by 821938089** [comment]
Where is Series?
Can you send a screenshot?

**Comment by OshekharO** [comment]
> Where is Series? Can you send a screenshot?

![Screenshot_2022-12-16-18-08-52-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/95137948/208100135-fc460e09-6823-4448-9171-e09b2b80f6ee.jpg)
I mean to say these ones are not showing.

**Comment by 821938089** [comment]
It show for me.
Are you using the beta version?

![image](https://user-images.githubusercontent.com/8674809/208103380-963ac75b-2806-4949-9301-3a3a6a4f8bb9.png)

**Comment by OshekharO** [comment]
> It show for me. Are you using the beta version?
> 
> ![image](https://user-images.githubusercontent.com/8674809/208103380-963ac75b-2806-4949-9301-3a3a6a4f8bb9.png)

Yes me using cloudstream beta

**Comment by OshekharO** [comment]
![Screenshot_2022-12-16-18-47-44-60_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/95137948/208106877-caff4be8-f68d-4f4e-9663-a2d5e634d00f.jpg)

**Comment by 821938089** [comment]
This is not Bollyzone. It seem is Desicinemas?

**Comment by OshekharO** [comment]
> This is not Bollyzone. It seem is Desicinemas?

Yes, because bollyzone provider not showing 
![Screenshot_2022-12-16-19-09-38-95_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/95137948/208110637-d843656d-ddf3-4340-9577-b08d59d6b623.jpg)

**Comment by OshekharO** [comment]
> This is not Bollyzone. It seem is Desicinemas?

Oh wait now it's working had to clear data of cloudstream.

**Comment by 821938089** [comment]
Desicinemas and Bollyzone in one extension (named Desicinemas).
