### ISSUE TITLE
[Site Request] High Priority (English)

### ISSUE THREAD

**Issue by RainbowSaga** [821938089/cloudstream-extensions#12]
## index site
- https://drive.gamick.workers.dev/0:/ have true quality even 4k
- https://rinzry.stream/0:/ have big collection with highest quality

## premium site
- https://ww1.new-movies123.co/

how to bypass premium quality -> replace 360 with 720, 1080, 1440 or 2160

_free :_ https://stream-1-1-ip4.loadshare.org/slice/9/VideoID-fntWp6zJ/ThaTlu/ZycbwU/hQjGMQ/dQbPtB/360?name=the-last-of-us-season-1-episode-03-long-long-time_360&token=ip=10.172.27.23~st=1675070094~exp=1675084494~acl=/*~hmac=2ae0030a21b52f2ccf5de463c2203b3c22aad45a0297e238107b72b3427cf948

_premium :_ https://stream-1-1-ip4.loadshare.org/slice/9/VideoID-fntWp6zJ/ThaTlu/ZycbwU/hQjGMQ/dQbPtB/2160?name=the-last-of-us-season-1-episode-03-long-long-time_2160&token=ip=10.172.27.23~st=1675070094~exp=1675084494~acl=/*~hmac=2ae0030a21b52f2ccf5de463c2203b3c22aad45a0297e238107b72b3427cf948

**_ps: this link may not work due to expired_**

Thanks 🙏

**Comment by 821938089** [comment]
added
