### ISSUE TITLE
请教下cs3添加拓展的方法,路径能用gitee等托管平台么?

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [821938089/cloudstream-extensions#17]
想把cs3给家人用,发现添加拓展要翻墙,大概看了下cs3代码,没太搞懂拉取您这拓展的方法,是 通过 
`cloudstream {
        setRepo(System.getenv("GITHUB_REPOSITORY") ?: "https://github.com/user/repo") // 这个路径么
    }`   
请教下如果是gitee的路径是否可以不用翻墙就能添加拓展源呢

**Comment by 821938089** [comment]
不能用gitee，这个访问是要登录的
建议用github代理

setRepo参数可以看下这里的源码第29行
https://github.com/recloudstream/gradle/blob/master/src/main/kotlin/com/lagradost/cloudstream3/gradle/CloudstreamExtension.kt

**Comment by XiaoRanLiu3119** [comment]
> 不能用gitee，这个访问是要登录的 建议用github代理
> 
> setRepo参数可以看下这里的源码第29行 https://github.com/recloudstream/gradle/blob/master/src/main/kotlin/com/lagradost/cloudstream3/gradle/CloudstreamExtension.kt

感谢感谢,我研究下代理
