### ISSUE TITLE
Live tv

### ISSUE THREAD

**Issue by bensmithgb53** [821938089/cloudstream-extensions#19]
Hello, please could you add this website please

https://streameast.top/

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/223443747-0b8270a7-8ec9-44b4-98c2-c7d6d01cd117.png)
still cant see any stream.

**Comment by bensmithgb53** [comment]
Oh I seen now. Streams only come on when the games are on. The streams are not there all the time. Is this bad?

**Comment by 821938089** [comment]
Looks like it's working well, I'll try to make it.

**Comment by bensmithgb53** [comment]
> Looks like it's working well, I'll try to make it.

Thank you! Is it hard to make it because I would love to learn how?

**Comment by bensmithgb53** [comment]
> added

No way than you so so much! You are you best man. Quick too

**Comment by bensmithgb53** [comment]
> > added
> 
> No way thank you so so much! You are you best man. Quick too

Please could you teach me or make a vidoe of you making one so I am try and learn please?

**Comment by 821938089** [comment]
i dont know how to tech you. 
but cs3 has a doc for dev, you can take a look at https://docs.cloudstream.cf/devs/gettingstarted/.
You can also join the cs3 discord to ask questions about making extensions, there are many developers in there who may be able to answer your questions.

**Comment by bensmithgb53** [comment]
> i dont know how to tech you. 
> but cs3 has a doc for dev, you can take a look at https://docs.cloudstream.cf/devs/gettingstarted/.
> You can also join the cs3 discord to ask questions about making extensions, there are many developers in there who may be able to answer your questions.

Noway to make a video of you making a repo for website and upload it so I get the basic understanding, no worries if not? There's no vidoes anywhere about cloudstream. 

It just saves asking you or anyone else to code websites over and over again. 

Rainostreams was down most of the night for me so I couldn't watch live TV but it's back up now. I have many more websites I can tell you about.
