### ISSUE TITLE
Live TV request 

### ISSUE THREAD

**Issue by bensmithgb53** [821938089/cloudstream-extensions#21]
Hello, would you add this website too please

https://1stream.eu/

I'm getting isp blocked too is there anyway to bypass this without Vpn?

**Comment by 821938089** [comment]
Can't bypass.

**Comment by bensmithgb53** [comment]
> Can't bypass.

Can you do that new website for me please? Because that other one works but sometimes it drops and I think this new website used different source.

**Comment by 821938089** [comment]
There are no playable streams on this site.
All categories are empty.

**Comment by bensmithgb53** [comment]
> There are no playable streams on this site.
> All categories are empty.

They come on hour before. Do they need to be active all the time or can you wait for one stream to play the grab all links?

**Comment by 821938089** [comment]
I don't know when will have stream.
It's best to always have a stream to grab.

**Comment by bensmithgb53** [comment]
> I don't know when will have stream.
> It's best to always have a stream to grab.

Hello mate streams are up on that website now hopefully it's possible.

**Comment by 821938089** [comment]
added

**Comment by bensmithgb53** [comment]
Cheers mate! Your the best
