### ISSUE TITLE
Slight Improvement in Netflix Mirror

### ISSUE THREAD

**Issue by SaurabhKaperwan** [821938089/cloudstream-extensions#34]
Netflix Mirror extension only support stream upto 720p but we can enable 1080p in website
![Screenshot_2023-09-15-19-10-31-15_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/821938089/cloudstream-extensions/assets/91174352/38b3aa2b-3a00-4d7d-bd71-1e29bc1ece60)

**Comment by 821938089** [comment]
Fixed
