### ISSUE TITLE
New extension request 

### ISSUE THREAD

**Issue by SaurabhKaperwan** [821938089/cloudstream-extensions#36]
https://world4ufree.codes/
For downloading there are so many jumps but website have watch online option ![Screenshot_2023-09-19-08-50-29-13_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/821938089/cloudstream-extensions/assets/91174352/df59bce8-98b0-4f4a-a693-b827b180a0f4)

This website also have same watch online option:
https://themoviesflix.se.net/

**Comment by 821938089** [comment]
You can go to Hexated Repo and open the issue, this style of player is better suited to be added to the SoraStream extension.
