### ISSUE TITLE
Some titles in Netflixmirror are not showing the cover poster images for some reason

### ISSUE THREAD

**Issue by Rayforest** [821938089/cloudstream-extensions#37]
Been like this for about a day now

**Comment by SaurabhKaperwan** [comment]
Don't use dns

**Comment by Rayforest** [comment]
The site is down rn. So yeah 🥹

**Comment by SaurabhKaperwan** [comment]
It is not down

**Comment by Rayforest** [comment]
> It is not down!

It is!

![Screenshot_2023-10-03-15-58-07-29_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/821938089/cloudstream-extensions/assets/124686957/11755506-33d2-4284-8889-2ac526f7b835)
