### ISSUE TITLE
New extension request

### ISSUE THREAD

**Issue by aadio7** [821938089/cloudstream-extensions#42]
https://mkvcinemas.dad/ as extension it has content in highest quality(there are webdl,bluray and webrip formats link) ...

https://github.com/TechShreyash/MkvCinemas-Scrapper .....its a scrapper(hope it helps)..

**Comment by 821938089** [comment]
Actual links require complex jumps. This scrapper uses someone else's API.

**Comment by aadio7** [comment]
> Actual links require complex jumps. This scrapper uses someone else's API.

Yaa the api is of the guy who uploaded the scrapper..
